package com.example.guesswho.constants

import androidx.core.content.ContextCompat.getDrawable
import com.example.guesswho.R

object Singleton{
    val characters = mutableListOf<Character>()
    val questions = mutableListOf<String>()
    init {
        characters.add(0,Character("Baby Bowser", R.drawable.babybowser))
        characters.add(1,Character("Bayonetta", R.drawable.bayonetta))
        characters.add(2,Character("Bowser", R.drawable.bowser))
        characters.add(3,Character("Byleth", R.drawable.byleth))
        characters.add(4,Character("Captain Falcon", R.drawable.captainfalcon))
        characters.add(5,Character("Cloud", R.drawable.cloud))
        characters.add(6,Character("Corrin", R.drawable.corrin))
        characters.add(7,Character("Dark Samus", R.drawable.darksamus))
        characters.add(8,Character("Diddy Kong", R.drawable.diddykong))
        characters.add(9,Character("Donkey Kong", R.drawable.dk))
        characters.add(10,Character("Dr. Mario", R.drawable.drmario))
        characters.add(11,Character("Duck Hunt", R.drawable.duckhunt))
        characters.add(12,Character("Falco", R.drawable.falco))
        characters.add(13,Character("Fox", R.drawable.fox))
        characters.add(14,Character("Ganon", R.drawable.ganon))
        characters.add(15,Character("Greninja", R.drawable.greninja))
        characters.add(16,Character("Ice Climbers", R.drawable.iceclimbers))
        characters.add(17,Character("Incineroar", R.drawable.incineroar))
        characters.add(18,Character("Jigglypuff", R.drawable.jigglypuff))
        characters.add(19,Character("Ken", R.drawable.ken))
        characters.add(20,Character("King Dedede", R.drawable.kingdedede))
        characters.add(21,Character("King K. Rool", R.drawable.kingkrool))
        characters.add(22,Character("Kirby", R.drawable.kirby))
        characters.add(23,Character("Link", R.drawable.link))
        characters.add(24,Character("Little Mac", R.drawable.littlemac))
        characters.add(25,Character("Lucario", R.drawable.lucario))
        characters.add(26,Character("Lucas", R.drawable.lucas))
        characters.add(27,Character("Lucina", R.drawable.lucina))
        characters.add(28,Character("Luigi", R.drawable.luigi))
        characters.add(29,Character("Mario", R.drawable.mario))
        characters.add(30,Character("Marth", R.drawable.marth))
        characters.add(31,Character("Megaman", R.drawable.megaman))
        characters.add(32,Character("Meta Knight", R.drawable.metaknight))
        characters.add(33,Character("Mewtwo", R.drawable.mewtwo))
        characters.add(34,Character("Mii Fighter", R.drawable.miifighter))
        characters.add(35,Character("Mr. Game and Watch", R.drawable.mrgameandwatch))
        characters.add(36,Character("Ness", R.drawable.ness))
        characters.add(37,Character("Pacman", R.drawable.pacman))
        characters.add(38,Character("Palutena", R.drawable.palutena))
        characters.add(39,Character("Pichu", R.drawable.pichu))
        characters.add(40,Character("Pikachu", R.drawable.pikachu))
        characters.add(41,Character("Pit", R.drawable.pit))
        characters.add(42,Character("Pokemon Trainer", R.drawable.pokemontrainer))
        characters.add(43,Character("Princess Daisy", R.drawable.princessdaisy))
        characters.add(44,Character("Princess Peach", R.drawable.princesspeach))
        characters.add(45,Character("Princess Rosalina", R.drawable.princessrosalina))
        characters.add(46,Character("Richter Belmont", R.drawable.richterbelmont))
        characters.add(47,Character("Ridley", R.drawable.ridley))
        characters.add(48,Character("Rob", R.drawable.rob))
        characters.add(49,Character("Roy", R.drawable.roy))
        characters.add(50,Character("Ryu", R.drawable.ryu))
        characters.add(51,Character("Samus", R.drawable.samus))
        characters.add(52,Character("Sheik", R.drawable.sheik))
        characters.add(53,Character("Shulk", R.drawable.shulk))
        characters.add(54,Character("Simon Belmont", R.drawable.simonbelmont))
        characters.add(55,Character("Snake", R.drawable.snake))
        characters.add(56,Character("Sonic", R.drawable.sonic))
        characters.add(57,Character("Squid Girl", R.drawable.squidgirl))
        characters.add(58,Character("Toon Link", R.drawable.toonlink))
        characters.add(59,Character("Villager", R.drawable.villager))
        characters.add(60,Character("Wario", R.drawable.wario))
        characters.add(61,Character("Wii Fit Trainer", R.drawable.wiifittrainer))
        characters.add(62,Character("Wolf", R.drawable.wolf))
        characters.add(63,Character("Yoshi", R.drawable.yoshi))
        characters.add(64,Character("Young Link", R.drawable.younglink))
        characters.add(65,Character("Zelda", R.drawable.zelda))
        characters.add(66,Character("Zero Suit Samus", R.drawable.zerosuitsamus))
        questions.add(0,"Is the character a human?")
        questions.add(1, "Is the character a Male?")
        questions.add(2, "Is the character Good?")
        questions.add(3, "Is the character wearing something on their head?")
        questions.add(4, "Does the character have Hair?")
        questions.add(5, "Does the character wear Clothes?")
        questions.add(6, "Does the character talk?")
        questions.add(7, "Can the character use supernatural abilities?")
        questions.add(8, "Is the character high-tech?")
        initQuestions()
    }

    fun getCharacter(index: Int): Character{
        return characters[index];
    }

    fun getCharacterQuestion(index: Int, questionIndex: Int): Boolean{
        return characters[index].getQuestion(questionIndex)
    }

    fun getQuestion(index: Int): String{
        return questions[index]
    }

    fun getNumberOfQuestions(): Int{
        var i = 0
        for (question in questions){
            i++
        }
        return i
    }

    fun getNumberOfCharacters(): Int{
        var i = 0
        for (character in characters){
            i++
        }
        return i
    }

    private fun initQuestions(){
        characters[1].setQuestion(0)
        characters[3].setQuestion(0)
        characters[4].setQuestion(0)
        characters[5].setQuestion(0)
        characters[6].setQuestion(0)
        characters[10].setQuestion(0)
        characters[14].setQuestion(0)
        characters[16].setQuestion(0)
        characters[19].setQuestion(0)
        characters[23].setQuestion(0)
        characters[24].setQuestion(0)
        characters[27].setQuestion(0)
        characters[28].setQuestion(0)
        characters[29].setQuestion(0)
        characters[30].setQuestion(0)
        characters[34].setQuestion(0)
        characters[36].setQuestion(0)
        characters[42].setQuestion(0)
        characters[43].setQuestion(0)
        characters[44].setQuestion(0)
        characters[45].setQuestion(0)
        characters[46].setQuestion(0)
        characters[49].setQuestion(0)
        characters[50].setQuestion(0)
        characters[51].setQuestion(0)
        characters[52].setQuestion(0)
        characters[53].setQuestion(0)
        characters[54].setQuestion(0)
        characters[55].setQuestion(0)
        characters[58].setQuestion(0)
        characters[59].setQuestion(0)
        characters[60].setQuestion(0)
        characters[61].setQuestion(0)
        characters[64].setQuestion(0)
        characters[65].setQuestion(0)
        characters[66].setQuestion(0)
        characters[0].setQuestion(1)
        characters[2].setQuestion(1)
        characters[3].setQuestion(1)
        characters[4].setQuestion(1)
        characters[5].setQuestion(1)
        characters[8].setQuestion(1)
        characters[9].setQuestion(1)
        characters[10].setQuestion(1)
        characters[11].setQuestion(1)
        characters[12].setQuestion(1)
        characters[13].setQuestion(1)
        characters[14].setQuestion(1)
        characters[19].setQuestion(1)
        characters[20].setQuestion(1)
        characters[21].setQuestion(1)
        characters[23].setQuestion(1)
        characters[24].setQuestion(1)
        characters[26].setQuestion(1)
        characters[28].setQuestion(1)
        characters[29].setQuestion(1)
        characters[30].setQuestion(1)
        characters[36].setQuestion(1)
        characters[37].setQuestion(1)
        characters[41].setQuestion(1)
        characters[42].setQuestion(1)
        characters[46].setQuestion(1)
        characters[49].setQuestion(1)
        characters[50].setQuestion(1)
        characters[53].setQuestion(1)
        characters[54].setQuestion(1)
        characters[55].setQuestion(1)
        characters[56].setQuestion(1)
        characters[58].setQuestion(1)
        characters[60].setQuestion(1)
        characters[62].setQuestion(1)
        characters[64].setQuestion(1)
        characters[1].setQuestion(2)
        characters[3].setQuestion(2)
        characters[4].setQuestion(2)
        characters[5].setQuestion(2)
        characters[6].setQuestion(2)
        characters[8].setQuestion(2)
        characters[9].setQuestion(2)
        characters[10].setQuestion(2)
        characters[12].setQuestion(2)
        characters[13].setQuestion(2)
        characters[19].setQuestion(2)
        characters[22].setQuestion(2)
        characters[23].setQuestion(2)
        characters[24].setQuestion(2)
        characters[26].setQuestion(2)
        characters[27].setQuestion(2)
        characters[28].setQuestion(2)
        characters[29].setQuestion(2)
        characters[30].setQuestion(2)
        characters[31].setQuestion(2)
        characters[36].setQuestion(2)
        characters[38].setQuestion(2)
        characters[41].setQuestion(2)
        characters[42].setQuestion(2)
        characters[43].setQuestion(2)
        characters[44].setQuestion(2)
        characters[45].setQuestion(2)
        characters[46].setQuestion(2)
        characters[49].setQuestion(2)
        characters[50].setQuestion(2)
        characters[51].setQuestion(2)
        characters[52].setQuestion(2)
        characters[53].setQuestion(2)
        characters[54].setQuestion(2)
        characters[55].setQuestion(2)
        characters[56].setQuestion(2)
        characters[58].setQuestion(2)
        characters[59].setQuestion(2)
        characters[63].setQuestion(2)
        characters[64].setQuestion(2)
        characters[65].setQuestion(2)
        characters[66].setQuestion(2)
        characters[4].setQuestion(3)
        characters[7].setQuestion(3)
        characters[10].setQuestion(3)
        characters[11].setQuestion(3)
        characters[16].setQuestion(3)
        characters[20].setQuestion(3)
        characters[21].setQuestion(3)
        characters[23].setQuestion(3)
        characters[27].setQuestion(3)
        characters[31].setQuestion(3)
        characters[36].setQuestion(3)
        characters[38].setQuestion(3)
        characters[41].setQuestion(3)
        characters[43].setQuestion(3)
        characters[44].setQuestion(3)
        characters[45].setQuestion(3)
        characters[46].setQuestion(3)
        characters[49].setQuestion(3)
        characters[50].setQuestion(3)
        characters[51].setQuestion(3)
        characters[52].setQuestion(3)
        characters[54].setQuestion(3)
        characters[55].setQuestion(3)
        characters[58].setQuestion(3)
        characters[60].setQuestion(3)
        characters[64].setQuestion(3)
        characters[65].setQuestion(3)
        characters[0].setQuestion(4)
        characters[1].setQuestion(4)
        characters[2].setQuestion(4)
        characters[3].setQuestion(4)
        characters[5].setQuestion(4)
        characters[6].setQuestion(4)
        characters[10].setQuestion(4)
        characters[16].setQuestion(4)
        characters[19].setQuestion(4)
        characters[23].setQuestion(4)
        characters[24].setQuestion(4)
        characters[26].setQuestion(4)
        characters[27].setQuestion(4)
        characters[28].setQuestion(4)
        characters[29].setQuestion(4)
        characters[30].setQuestion(4)
        characters[34].setQuestion(4)
        characters[36].setQuestion(4)
        characters[38].setQuestion(4)
        characters[41].setQuestion(4)
        characters[42].setQuestion(4)
        characters[43].setQuestion(4)
        characters[44].setQuestion(4)
        characters[45].setQuestion(4)
        characters[46].setQuestion(4)
        characters[49].setQuestion(4)
        characters[50].setQuestion(4)
        characters[51].setQuestion(4)
        characters[52].setQuestion(4)
        characters[53].setQuestion(4)
        characters[54].setQuestion(4)
        characters[55].setQuestion(4)
        characters[58].setQuestion(4)
        characters[59].setQuestion(4)
        characters[60].setQuestion(4)
        characters[61].setQuestion(4)
        characters[64].setQuestion(4)
        characters[65].setQuestion(4)
        characters[66].setQuestion(4)
        characters[1].setQuestion(5)
        characters[3].setQuestion(5)
        characters[4].setQuestion(5)
        characters[5].setQuestion(5)
        characters[6].setQuestion(5)
        characters[7].setQuestion(5)
        characters[10].setQuestion(5)
        characters[12].setQuestion(5)
        characters[13].setQuestion(5)
        characters[14].setQuestion(5)
        characters[16].setQuestion(5)
        characters[19].setQuestion(5)
        characters[20].setQuestion(5)
        characters[21].setQuestion(5)
        characters[23].setQuestion(5)
        characters[24].setQuestion(5)
        characters[26].setQuestion(5)
        characters[27].setQuestion(5)
        characters[28].setQuestion(5)
        characters[29].setQuestion(5)
        characters[30].setQuestion(5)
        characters[32].setQuestion(5)
        characters[34].setQuestion(5)
        characters[36].setQuestion(5)
        characters[37].setQuestion(5)
        characters[38].setQuestion(5)
        characters[41].setQuestion(5)
        characters[42].setQuestion(5)
        characters[43].setQuestion(5)
        characters[44].setQuestion(5)
        characters[45].setQuestion(5)
        characters[46].setQuestion(5)
        characters[49].setQuestion(5)
        characters[50].setQuestion(5)
        characters[51].setQuestion(5)
        characters[52].setQuestion(5)
        characters[53].setQuestion(5)
        characters[54].setQuestion(5)
        characters[55].setQuestion(5)
        characters[56].setQuestion(5)
        characters[57].setQuestion(5)
        characters[58].setQuestion(5)
        characters[59].setQuestion(5)
        characters[60].setQuestion(5)
        characters[61].setQuestion(5)
        characters[62].setQuestion(5)
        characters[64].setQuestion(5)
        characters[65].setQuestion(5)
        characters[66].setQuestion(5)
        characters[0].setQuestion(6)
        characters[1].setQuestion(6)
        characters[2].setQuestion(6)
        characters[3].setQuestion(6)
        characters[5].setQuestion(6)
        characters[6].setQuestion(6)
        characters[8].setQuestion(6)
        characters[9].setQuestion(6)
        characters[10].setQuestion(6)
        characters[12].setQuestion(6)
        characters[13].setQuestion(6)
        characters[14].setQuestion(6)
        characters[19].setQuestion(6)
        characters[21].setQuestion(6)
        characters[26].setQuestion(6)
        characters[27].setQuestion(6)
        characters[28].setQuestion(6)
        characters[29].setQuestion(6)
        characters[30].setQuestion(6)
        characters[31].setQuestion(6)
        characters[33].setQuestion(6)
        characters[38].setQuestion(6)
        characters[41].setQuestion(6)
        characters[43].setQuestion(6)
        characters[44].setQuestion(6)
        characters[45].setQuestion(6)
        characters[49].setQuestion(6)
        characters[50].setQuestion(6)
        characters[51].setQuestion(6)
        characters[52].setQuestion(6)
        characters[53].setQuestion(6)
        characters[55].setQuestion(6)
        characters[56].setQuestion(6)
        characters[60].setQuestion(6)
        characters[61].setQuestion(6)
        characters[62].setQuestion(6)
        characters[64].setQuestion(6)
        characters[65].setQuestion(6)
        characters[0].setQuestion(7)
        characters[1].setQuestion(7)
        characters[2].setQuestion(7)
        characters[3].setQuestion(7)
        characters[5].setQuestion(7)
        characters[6].setQuestion(7)
        characters[14].setQuestion(7)
        characters[15].setQuestion(7)
        characters[17].setQuestion(7)
        characters[18].setQuestion(7)
        characters[22].setQuestion(7)
        characters[23].setQuestion(7)
        characters[25].setQuestion(7)
        characters[26].setQuestion(7)
        characters[28].setQuestion(7)
        characters[29].setQuestion(7)
        characters[33].setQuestion(7)
        characters[34].setQuestion(7)
        characters[35].setQuestion(7)
        characters[36].setQuestion(7)
        characters[37].setQuestion(7)
        characters[38].setQuestion(7)
        characters[39].setQuestion(7)
        characters[40].setQuestion(7)
        characters[41].setQuestion(7)
        characters[45].setQuestion(7)
        characters[49].setQuestion(7)
        characters[52].setQuestion(7)
        characters[53].setQuestion(7)
        characters[58].setQuestion(7)
        characters[61].setQuestion(7)
        characters[64].setQuestion(7)
        characters[65].setQuestion(7)
        characters[1].setQuestion(8)
        characters[4].setQuestion(8)
        characters[5].setQuestion(8)
        characters[7].setQuestion(8)
        characters[10].setQuestion(8)
        characters[12].setQuestion(8)
        characters[13].setQuestion(8)
        characters[28].setQuestion(8)
        characters[31].setQuestion(8)
        characters[33].setQuestion(8)
        characters[42].setQuestion(8)
        characters[47].setQuestion(8)
        characters[48].setQuestion(8)
        characters[51].setQuestion(8)
        characters[53].setQuestion(8)
        characters[55].setQuestion(8)
        characters[57].setQuestion(8)
        characters[60].setQuestion(8)
        characters[62].setQuestion(8)
        characters[66].setQuestion(8)
    }

}